server:
  port: 9999
  servlet:
    context-path: /api
spring:
  application:
    name: hututu-intelligentImageBed
  profiles:
    active: local
  servlet:
    multipart:
      location: /users/varya/nacos
      max-file-size: 10MB # 默认上传大小为1MB


knife4j:
  enable: true
  openapi:
    title: 弧图图-智能图床

    email: whltaoin@163.com
    url: htt://www.varin.cn
    version: V1.0.0
    group:
      default:
        group-name: ""
        api-rule: package
        api-rule-resources:
          - cn.varin.hututu.controller